apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ticketing.fullname" . }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ticketing.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Postgres credentials
  POSTGRES_PASSWORD: "demo-pg-password-CHANGE-IN-PROD"

  # Redis password (postgres-style, opcionalno)
  REDIS_PASSWORD: "demo-redis-password-CHANGE-IN-PROD"

  # JWT secret (za buduce auth)
  JWT_SECRET: "demo-jwt-secret-CHANGE-IN-PROD"
