{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ticketing.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ticketing.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
